layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: wcdg
  # keybase: your_username
  linkedin: CarterRoeser
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 5056942
  # telegram: your_username
  twitter: cjroeser
  # unsplash: your_username
  # vk: your_username
  # website: http://cdgtech.one
  # youtube: CarterJRFilms
