#!/bin/bash
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
  OS=$(uname -s)
fi
if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ] || [ "$OS" == "Debian GNU/Linux" ]; then
  php -v
  lsb_release -a
  /usr/local/vesta/bin/v-list-sys-config
  /usr/local/vesta/bin/v-list-sys-services
elif [ "$OS" == "CentOS Linux"]; then
  php -v
  cat /etc/centos-release
  /usr/local/vesta/bin/v-list-sys-config
  /usr/local/vesta/bin/v-list-sys-services
elif [ "$OS" == "RHEL" ]; then
  php -v
  hostnamectl
  /usr/local/vesta/bin/v-list-sys-config
  /usr/local/vesta/bin/v-list-sys-services
else
  echo 'Error: Debian, Ubuntu, CentOS, or RHEL not detected. Exiting ...\n'
  exit 1
fi
