#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
    OS=$(uname -s)
fi

if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ] || [ "$OS" == "Debian GNU/Linux" ]; then 
	if [ ! -z "$(ls -A ./)" ]; then
		printf "Error: Directory not empty.\nVWI must be installed in clean directory. Exiting ...\n"
		exit 1
	fi
	printf "Checking for required packages ...\n"
	if dpkg -s wget &> /dev/null
        then
                echo "wget found"
        else
                echo "wget not found. Installing ..."
                apt-get install -y wget > /dev/null
        fi
        if dpkg -s tar &> /dev/null
        then
                echo "tar found"
        else
                echo "tar not found. Installing ..."
                apt-get install -y tar > /dev/null
        fi
        if dpkg -s git &> /dev/null
        then
                echo "git found"
        else
                echo "git not found. Installing ..."
                apt-get install -y git > /dev/null
        fi

	printf "\nInstalling Vesta Web Interface frontend ...\n"
	git clone --quiet https://github.com/cdgco/VestaWebInterface . > /dev/null
    git checkout --quiet 94b41e0 > /dev/null
	if [ -f README.md ] ; then
		rm README.md
	elif [ -f 'VWI Banner.png' ] ; then
		rm 'VWI Banner.png'
	fi
	chmod 777 includes
    chmod 777 tmp
    chmod 777 plugins/images/uploads
	printf "\nInstalling Language Packages ... (May take a while) \n"
	if [ ! `locale -a | grep 'ar_EG.utf8' &> /dev/null` ] ; then
		locale-gen ar_EG.utf8 &> /dev/null
	elif [ ! `locale -a | grep 'bs_BA.utf8' &> /dev/null` ] ; then
		locale-gen bs_BA.utf8
	elif [ ! `locale -a | grep 'cs_CZ.utf8' &> /dev/null` ] ; then
		locale-gen cs_CZ.utf8
	elif [ ! `locale -a | grep 'zh_CN.utf8' &> /dev/null` ] ; then
		locale-gen zh_CN.utf8
	elif [ ! `locale -a | grep 'da_DK.utf8' &> /dev/null` ] ; then
		locale-gen da_DK.utf8
	elif [ ! `locale -a | grep 'de_DE.utf8' &> /dev/null` ] ; then
		locale-gen de_DE.utf8
	elif [ ! `locale -a | grep 'el_GR.utf8' &> /dev/null` ] ; then
		locale-gen el_GR.utf8
	elif [ ! `locale -a | grep 'fa_IR' &> /dev/null` ] ; then
		locale-gen fa_IR
	elif [ ! `locale -a | grep 'fi_FI.utf8' &> /dev/null` ] ; then
		locale-gen fi_FI.utf8
	elif [ ! `locale -a | grep 'hu_HU.utf8' &> /dev/null` ] ; then
		locale-gen hu_HU.utf8
	elif [ ! `locale -a | grep 'id_ID.utf8' &> /dev/null` ] ; then
		locale-gen id_ID.utf8
	elif [ ! `locale -a | grep 'it_IT.utf8' &> /dev/null` ] ; then
		locale-gen it_IT.utf8
	elif [ ! `locale -a | grep 'ja_JP.utf8' &> /dev/null` ] ; then
		locale-gen ja_JP.utf8
	elif [ ! `locale -a | grep 'ka_GE.utf8' &> /dev/null` ] ; then
		locale-gen ka_GE.utf8
	elif [ ! `locale -a | grep 'nl_NL.utf8' &> /dev/null` ] ; then
		locale-gen nl_NL.utf8
	elif [ ! `locale -a | grep 'nn_NO.utf8' &> /dev/null` ] ; then
		locale-gen nn_NO.utf8
	elif [ ! `locale -a | grep 'pl_PL.utf8' &> /dev/null` ] ; then
		locale-gen pl_PL.utf8
	elif [ ! `locale -a | grep 'pt_BR.utf8' &> /dev/null` ] ; then
		locale-gen pt_BR.utf8
	elif [ ! `locale -a | grep 'pt_PT.utf8' &> /dev/null` ] ; then
		locale-gen pt_PT.utf8
	elif [ ! `locale -a | grep 'ro_RO.utf8' &> /dev/null` ] ; then
		locale-gen ro_RO.utf8
	elif [ ! `locale -a | grep 'ru_RU.utf8' &> /dev/null` ] ; then
		locale-gen ru_RU.utf8
	elif [ ! `locale -a | grep 'sv_SE.utf8' &> /dev/null` ] ; then
		locale-gen sv_SE.utf8
	elif [ ! `locale -a | grep 'tr_TR.utf8' &> /dev/null` ] ; then
		locale-gen tr_TR.utf8
	elif [ ! `locale -a | grep 'zh_TW.utf8' &> /dev/null` ] ; then
		locale-gen zh_TW.utf8
	elif [ ! `locale -a | grep 'uk_UA.utf8' &> /dev/null` ] ; then
		locale-gen uk_UA.utf8
	elif [ ! `locale -a | grep 'vi_VN' &> /dev/null` ] ; then
		locale-gen vi_VN
	elif [ ! `locale -a | grep 'es_US.utf8' &> /dev/null` ] ; then
		locale-gen es_US.utf8
	elif [ ! `locale -a | grep 'en_US.utf8' &> /dev/null` ] ; then
		locale-gen en_US.utf8
	elif [ ! `locale -a | grep 'fr_FR.utf8' &> /dev/null` ] ; then
		locale-gen fr_FR.utf8
	else
		printf "All languages already installed \n"
	fi
	printf "Installing Vesta Web Interface backend ...\n"
	sleep .5
	if [ -d /usr/local/vesta/softaculous/enduser/themes/default ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/default /usr/local/vesta/softaculous/enduser/themes/original-default -r
	elif [ -d /usr/local/vesta/softaculous/enduser/themes/simple ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/simple /usr/local/vesta/softaculous/enduser/themes/original-simple -r
	fi
	wget -q https://github.com/cdgco/VestaWebInterface/releases/download/v0.5.3-Beta/backend.tar.gz
	if [ -f backend.tar.gz ] ; then
		tar -xzf backend.tar.gz -C /usr/local/
		rm backend.tar.gz
	fi
	read -p "Enter the full web address of your installation: "
        echo "<?php \$vwipanel = '$REPLY'; ?>" > /usr/local/vesta/web/vwi/config.php
	printf "\nInstallation Complete! Please visit your website online to finish configuration.\n"
elif [ "$OS" == "CentOS Linux" ] || [ "$OS" == "RHEL" ]; then
	if [ ! -z "$(ls -A ./)" ]; then
		printf "Error: Directory not empty.\nVWI must be installed in clean directory. Exiting ...\n"
		exit 1
	fi
	printf "Checking for required packages ...\n"
        if rpm -q wget &> /dev/null
	then
		echo "wget found"
	else
		echo "wget not found. Installing ..."
		yum -y install wget
	fi
	if rpm -q tar &> /dev/null
	then
		echo "tar found"
	else
		echo "tar not found. Installing ..."
		yum -y install tar
	fi
	if rpm -q git &> /dev/null
	then
		echo "git found"
	else
		echo "git not found. Installing ..."
		yum -y install git
	fi
	printf "\nInstalling Vesta Web Interface frontend ...\n"
	git clone --quiet https://github.com/cdgco/VestaWebInterface . > /dev/null
    git checkout --quiet 94b41e0 > /dev/null
	if [ -f README.md ] ; then
		rm README.md
	elif [ -f 'VWI Banner.png' ] ; then
		rm 'VWI Banner.png'
	fi
	chmod 777 includes
    chmod 777 tmp
    chmod 777 plugins/images/uploads
	printf "Installing Vesta Web Interface backend ...\n"
	sleep .5
	if [ -d /usr/local/vesta/softaculous/enduser/themes/default ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/default /usr/local/vesta/softaculous/enduser/themes/original-default -r
	elif [ -d /usr/local/vesta/softaculous/enduser/themes/simple ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/simple /usr/local/vesta/softaculous/enduser/themes/original-simple -r
	fi
	wget -q https://github.com/cdgco/VestaWebInterface/releases/download/v0.5.3-Beta/backend.tar.gz
	if [ -f backend.tar.gz ] ; then
		tar -xzf backend.tar.gz -C /usr/local/
		rm backend.tar.gz
	fi
	read -p "Enter the full web address of your installation: "
        echo "<?php \$vwipanel = '$REPLY'; ?>" > /usr/local/vesta/web/vwi/config.php
	printf "\nInstallation Complete! Please visit your website online to finish configuration.\n"
else
	echo 'Error: VWI can only be installed on Debian, Ubuntu, CentOS, or RHEL. Exiting ...\n'
	exit 1
fi
