#!/bin/bash
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
  OS=$(uname -s)
fi
if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ] || [ "$OS" == "Debian GNU/Linux" ]; then
  lsb_release -a
  /usr/local/hestia/bin/v-list-sys-php
  /usr/local/hestia/bin/v-list-sys-php-config
  /usr/local/hestia/bin/v-list-sys-config
  /usr/local/hestia/bin/v-list-sys-services
else
  echo 'Error: Debian or Ubuntu not detected. Exiting ...\n'
  exit 1
fi
