#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
    OS=$(uname -s)
fi

if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ] ||  [ "$OS" == "Debian GNU/Linux" ]; then 
	printf "Checking for required packages ...\n"
	if dpkg -s wget &> /dev/null
        then
                echo "wget found"
        else
                echo "wget not found. Installing ..."
                apt-get install -y wget > /dev/null
        fi
        if dpkg -s tar &> /dev/null
        then
                echo "tar found"
        else
                echo "tar not found. Installing ..."
                apt-get install -y tar > /dev/null
        fi
	printf "Installing Hestia Web Interface backend ...\n"
	wget -q https://github.com/cdgco/HestiaWebInterface/releases/download/v1.0.0/backend.tar.gz
	if [ -f backend.tar.gz ] ; then
		tar -xzf backend.tar.gz -C /usr/local/
		rm backend.tar.gz
	fi
	printf "\nInstallation Complete! Please visit your website online to finish configuration.\n"
else
	echo 'Error: HWI can only be installed on Debian or Ubuntu. Exiting ...\n'
	exit 1
fi
