#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
    OS=$(uname -s)
fi

if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ] || [ "$OS" == "Debian GNU/Linux" ]; then 
	printf "\nForce Installing Language Packages ... (May take a while) \n"
	sed -i 's/^# *\(ar_EG.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(bs_BA.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(cs_CZ.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(zh_CN.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(da_DK.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(de_DE.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(fa_IR.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(fi_FI.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(hu_HU.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(id_ID.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(it_IT.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(ja_JP.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(ka_GE.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(nl_NL.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(nn_NO.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(pl_PL.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(pt_BR.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(pt_PT.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(ro_RO.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(ru_RU.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(sv_SE.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(tr_TR.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(zh_TW.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(uk_UA.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(vi_VN.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(es_US.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
	sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen
	
	
	locale-gen ar_EG.utf8 > /dev/null
	locale-gen bs_BA.utf8 > /dev/null
	locale-gen cs_CZ.utf8 > /dev/null
	locale-gen zh_CN.utf8 > /dev/null
	locale-gen da_DK.utf8 > /dev/null
	locale-gen de_DE.utf8 > /dev/null
	locale-gen el_GR.utf8 > /dev/null
	locale-gen fa_IR.utf8 > /dev/null
	locale-gen fi_FI.utf8 > /dev/null
	locale-gen hu_HU.utf8 > /dev/null
	locale-gen id_ID.utf8 > /dev/null
	locale-gen it_IT.utf8 > /dev/null
	locale-gen ja_JP.utf8 > /dev/null
	locale-gen ka_GE.utf8 > /dev/null
	locale-gen nl_NL.utf8 > /dev/null
	locale-gen nn_NO.utf8 > /dev/null
	locale-gen pl_PL.utf8 > /dev/null
	locale-gen pt_BR.utf8 > /dev/null
	locale-gen pt_PT.utf8 > /dev/null
	locale-gen ro_RO.utf8 > /dev/null
	locale-gen ru_RU.utf8 > /dev/null
	locale-gen sv_SE.utf8 > /dev/null
	locale-gen tr_TR.utf8 > /dev/null
	locale-gen zh_TW.utf8 > /dev/null
	locale-gen uk_UA.utf8 > /dev/null
	locale-gen vi_VN.utf8 > /dev/null
	locale-gen es_US.utf8 > /dev/null
	locale-gen en_US.utf8 > /dev/null
	locale-gen fr_FR.utf8 > /dev/null
	printf "\nInstallation Complete!\n"
elif [ "$OS" == "CentOS Linux" ] || [ "$OS" == "RHEL" ]; then
	printf "Language Packages not necessary for CentOS or RHEL. Exiting ...\n"
  exit 1
else
	printf "Error: VWI can only be installed on Debian, Ubuntu, CentOS, or RHEL. Exiting ...\n"
	exit 1
fi
