#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
    OS=Debian
elif [ -f /etc/redhat-release ]; then
    OS=RHEL
else
    OS=$(uname -s)
fi

if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ]; then 
	printf "\nInstalling Language Packages ...\n"
	locale-gen ar_EG.utf8
	locale-gen bs_BA.utf8
	locale-gen cs_CZ.utf8
	locale-gen zh_CN.utf8
	locale-gen da_DK.utf8
	locale-gen de_DE.utf8
	locale-gen el_GR.utf8
	locale-gen fa_IR
	locale-gen fi_FI.utf8
	locale-gen hu_HU.utf8
	locale-gen id_ID.utf8
	locale-gen it_IT.utf8
	locale-gen ja_JP.utf8
	locale-gen ka_GE.utf8
	locale-gen nl_NL.utf8
	locale-gen nn_NO.utf8
	locale-gen pl_PL.utf8
	locale-gen pt_BR.utf8
	locale-gen pt_PT.utf8
	locale-gen ro_RO.utf8
	locale-gen ru_RU.utf8
	locale-gen sv_SE.utf8
	locale-gen tr_TR.utf8
	locale-gen zh_TW.utf8
	locale-gen uk_UA.utf8
	locale-gen vi_VN
	locale-gen es_US.utf8
	locale-gen en_US.utf8
	locale-gen fr_FR.utf8
	printf "\nInstallation Complete!\n"
elif [ "$OS" == "CentOS Linux" ] || [ "$OS" == "RHEL" ]; then
	printf "Language Packages not necessary for CentOS or RHEL. Exiting ...\n"
  exit 1
else
	printf "Error: VWI can only be installed on Debian, Ubuntu, CentOS, or RHEL. Exiting ...\n"
	exit 1
fi
