#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
fi
printf "\nUninstalling Vesta Web Interface backend ...\n"
if [ -f /usr/local/vesta/web/templates/r_1.php ] ; then
  rm /usr/local/vesta/web/templates/r_1.php
fi
if [ -f /usr/local/vesta/web/templates/r_2.php ] ; then
  rm /usr/local/vesta/web/templates/r_2.php
fi
if [ -f /usr/local/vesta/web/templates/r_3.php ] ; then
  rm /usr/local/vesta/web/templates/r_3.php
fi
if [ -f /usr/local/vesta/web/reset/reset.php ] ; then
  rm /usr/local/vesta/web/reset/reset.php
fi
if [ -f /usr/local/vesta/web/list/rrd/vwi.php ] ; then
  rm /usr/local/vesta/web/list/rrd/vwi.php
fi
if [ -f /usr/local/vesta/web/download/backup/vwi.php ] ; then
  rm /usr/local/vesta/web/download/backup/vwi.php
fi
if [ -f /usr/local/vesta/web/login/vwi.php ] ; then
  rm /usr/local/vesta/web/login/vwi.php
fi
if [ -f /usr/local/vesta/web/inc/main-cdg.php ] ; then
  rm /usr/local/vesta/web/inc/main-cdg.php
fi
if [ -f /usr/local/vesta/web/inc/i18n-cdg.php ] ; then
  rm /usr/local/vesta/web/inc/i18n-cdg.php
fi
if [ -d /usr/local/vesta/web/inc/i18n-cdg ] ; then
  rm /usr/local/vesta/web/inc/i18n-cdg -r
fi
if [ -d /usr/local/vesta/web/vwi ] ; then
  rm /usr/local/vesta/web/vwi -r
fi
if [ -d /usr/local/vesta/softaculous/enduser/themes/default ] ; then
  rm /usr/local/vesta/softaculous/enduser/themes/deafult -r
fi
if [ -d /usr/local/vesta/softaculous/enduser/themes/simple ] ; then
  rm /usr/local/vesta/softaculous/enduser/themes/simple -r
fi
if [ -d /usr/local/vesta/softaculous/enduser/themes/original-default ] ; then
  mv /usr/local/vesta/softaculous/enduser/themes/original-default /usr/local/vesta/softaculous/enduser/themes/default -r
fi
if [ -d /usr/local/vesta/softaculous/enduser/themes/original-default ] ; then
  mv /usr/local/vesta/softaculous/enduser/themes/original-simple /usr/local/vesta/softaculous/enduser/themes/simple -r
fi
if [ -f /usr/local/vesta/bin/vwi-chmod-file-640 ] ; then
  rm /usr/local/vesta/bin/vwi-chmod-file-640
fi
if [ -f /usr/local/vesta/bin/vwi-chmod-file-644 ] ; then
  rm /usr/local/vesta/bin/vwi-chmod-file-644
fi
printf "\nProcess Complete!.\n\nWe are sorry to see you go.\nPlease consider letting us know why you are uninstalling at http://link.cdgtech.one/un.\n"
