#!/bin/bash

if [ "x$(id -u)" != 'x0' ]; then
	echo 'Error: this script can only be executed by root'
	exit 1
fi
printf "\nUninstalling Vesta Web Interface backend ...\n"
if [ -f /usr/local/vesta/web/templates/r_1.php ] ; then
  rm /usr/local/vesta/web/templates/r_1.php
elif [ -f /usr/local/vesta/web/templates/r_2.php ] ; then
  rm /usr/local/vesta/web/templates/r_2.php
elif [ -f /usr/local/vesta/web/templates/r_3.php ] ; then
  rm /usr/local/vesta/web/templates/r_3.php
elif [ -f /usr/local/vesta/web/reset/reset.php ] ; then
  rm /usr/local/vesta/web/reset/reset.php
elif [ -f /usr/local/vesta/web/list/rrd/vwi.php ] ; then
  rm /usr/local/vesta/web/list/rrd/vwi.php
elif [ -f /usr/local/vesta/web/login/backup.php ] ; then
  rm /usr/local/vesta/web/login/backup.php
elif [ -f /usr/local/vesta/web/inc/main-cdg.php ] ; then
  rm /usr/local/vesta/web/inc/main-cdg.php
elif [ -f /usr/local/vesta/web/inc/i18n-cdg.php ] ; then
  rm /usr/local/vesta/web/inc/i18n-cdg.php
elif [ -d /usr/local/vesta/web/inc/i18n-cdg ] ; then
  rm /usr/local/vesta/web/inc/i18n-cdg -r
elif [ -d /usr/local/vesta/web/vwi ] ; then
  rm /usr/local/vesta/web/vwi -r
elif [ -d /usr/local/vesta/softaculous/enduser/themes/default ] ; then
  rm /usr/local/vesta/softaculous/enduser/themes/deafult -r
elif [ -d /usr/local/vesta/softaculous/enduser/themes/simple ] ; then
  rm /usr/local/vesta/softaculous/enduser/themes/simple -r
elif [ -d /usr/local/vesta/softaculous/enduser/themes/original-default ] ; then
  mv /usr/local/vesta/softaculous/enduser/themes/original-default /usr/local/vesta/softaculous/enduser/themes/default -r
elif [ -d /usr/local/vesta/softaculous/enduser/themes/original-default ] ; then
  mv /usr/local/vesta/softaculous/enduser/themes/original-simple /usr/local/vesta/softaculous/enduser/themes/simple -r
elif [ -f /usr/local/vesta/bin/vwi-chmod-file-640 ] ; then
  rm /usr/local/vesta/bin/vwi-chmod-file-640
elif [ -f /usr/local/vesta/bin/vwi-chmod-file-644 ] ; then
  rm /usr/local/vesta/bin/vwi-chmod-file-644
fi
printf "\nProcess Complete!.\n"
